import type { Metadata } from "next";
import { FormProvider } from '@/store/FormContext';
import { UserContextProvider } from "@/store/UserContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <UserContextProvider>
          <FormProvider>
            {children}
          </FormProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
